# Site settings
author: Garrett Thompson
title: The Journey begins
header-img: img/home-bg.png
email: gtcruz.gt@gmail.com
copyright_name: Garrett Thompson
description: > # this means to ignore newlines until "baseurl:"
  First blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HiphopSamurai

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
